// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:userSlug": {
    params: {
      "userSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users" | "/users/:userSlug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/_usersLayout.tsx": {
    id: "routes/_usersLayout";
    page: "/users" | "/users/:userSlug";
  };
  "routes/users.index.tsx": {
    id: "routes/users.index";
    page: "/users";
  };
  "routes/users.$userSlug.tsx": {
    id: "routes/users.$userSlug";
    page: "/users/:userSlug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/_usersLayout": typeof import("./app/routes/_usersLayout.tsx");
  "routes/users.index": typeof import("./app/routes/users.index.tsx");
  "routes/users.$userSlug": typeof import("./app/routes/users.$userSlug.tsx");
};